version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./99-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    volumes:      
      - ./seeder:/docker-entrypoint-initdb.d/script.sql
